### ISSUE TITLE
X11 extension broken on multi-user systems

### ISSUE THREAD

**Issue by meyerj** [osrf/rocker#102]
The [`--x11` extension](https://github.com/osrf/rocker/blob/b4a736bfa98c409c5565ec3f77bc58673db7cbd0/src/rocker/nvidia_extension.py#L36) fails to run `xauth` on the host if the hard-coded `/tmp/.docker.xauth` already exists and has been created by another user (permissions are 0600):

```sh
xauth:  timeout in locking authority file /tmp/.docker.xauth
Failed setting up XAuthority with command xauth nlist localhost:11.0 | sed -e 's/^..../ffff/' | xauth -f /tmp/.docker.xauth nmerge -
Failed to precondition for extension [x11] with error: Command 'xauth nlist localhost:11.0 | sed -e 's/^..../ffff/' | xauth -f /tmp/.docker.xauth nmerge -' returned non-zero exit status 1.
deactivating
```

I suggest to create the file with [tempfile.mkstemp](https://docs.python.org/3.10/library/tempfile.html#tempfile.mkstemp) instead on the host, such that each rocker invocation is independent of previous runs:

https://github.com/osrf/rocker/blob/b4a736bfa98c409c5565ec3f77bc58673db7cbd0/src/rocker/nvidia_extension.py#L44

**Comment by tfoote** [comment]
Yeah, using a temporary directory makes sense. I thought they could share, but different users with different permissions definitely could cause problems.
