### ISSUE TITLE
`$HOME` environment incorrect in container

### ISSUE THREAD

**Issue by galou** [osrf/rocker#131]
When I run `rocker --user --home tiryoh/ros-melodic-desktop`, the `/home/gael` directory is created, the user `gael` is created but `$HOME` points to `/home/ubuntu`.

Beware, the docker image is quite large but I don't know which other smaller image would reproduce the issue.

**Comment by tfoote** [comment]
That's an interesting behavior. Something must be changing or setting the `$HOME` variable. I would look at the Dockerfile and the entrypoint scripts to debug.

I found what appears to be the Dockerfile for that image and you appear to be [setting it explicitly](https://github.com/Tiryoh/docker-ros-melodic-desktop/blob/ca6e932d9586f84909b45e76f90cae3455ab80e6/base/Dockerfile#L19) 

If you set it in your Dockerfile it will override the default which is picked up from your user's defaults. If explicitly set we don't want to override it unless the user explicitly sets it again. 

In general that whole user section would probably be better to not be baked into the image.
