### ISSUE TITLE
Option for hostname

### ISSUE THREAD

**Issue by StefanFabian** [osrf/rocker#153]
First off, thank you so much for your work on this!
I have just a minor nitpick that I'm currently getting around with the also cool off-your-rocker package.
Currently, there is no option to set the hostname of the container.
That seems like a useful argument to have.

**Comment by kanishchugh** [comment]
Hi, I would like to take over this issue. as i am a new developer is there anything you would like to suggest me to tackle this problem?

**Comment by tfoote** [comment]
@kanishchugh You'll want to create a new extension for rocker which will add a hostname argument and then create the run arguments to set the hostname. It should look a lot like the Name extension: https://github.com/osrf/rocker/blob/0fde53b0f6a2ff5f6e17496b52b934a09fcd0bda/src/rocker/extensions.py#L94
