### ISSUE TITLE
Check for minimum version of docker-py necessary

### ISSUE THREAD

**Issue by tfoote** [osrf/rocker#16]
Users have run into issues which is likely too low a version on xenial: https://github.com/osrf/car_demo/issues/49#issuecomment-453711815

**Comment by JKTesla** [comment]
My system inf is:
> $ sudo lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial

> $ uname -a
Linux JK-Note 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

> $ nvidia-smi
Thu Jan 17 12:08:53 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+


satisfy these [requirement](https://github.com/osrf/rocker#nvidia-settings)

But ./run_demo.bash, the terminal told me；

> $ ./run_demo.bash 
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
Collecting git+https://github.com/osrf/rocker.git
  Cloning https://github.com/osrf/rocker.git to /tmp/pip-8461tp_x-build
Requirement already up-to-date: distro in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from rocker===0.1.3)
Requirement already up-to-date: docker-py in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from rocker===0.1.3)
…
Requirement already up-to-date: urllib3<1.25,>=1.21.1 in /tmp/car_demo_rocker_venv/lib/python3.5/site-packages (from requests!=2.11.0,>=2.5.2->docker-py->rocker===0.1.3)
Installing collected packages: rocker
  Found existing installation: rocker 0.1.3
    Uninstalling rocker-0.1.3:
      Successfully uninstalled rocker-0.1.3
  Running setup.py install for rocker ... done
Successfully installed rocker-0.1.3
You are using pip version 8.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Plugins found: ['dev_helpers', 'home', 'nvidia', 'pulse', 'user']
usage: rocker [-h] [--noexecute] [--nocache] [--pull]
              [--network {bridge,host,overlay,none}]
              [--devices [DEVICES [DEVICES ...]]] [--dev-helpers] [--home]
              [--nvidia] [--pulse] [--user]
              image [command [command ...]]
**rocker: error: unrecognized arguments: --exec**

I have no idea about this error.Hope someone give some advice.Thx.

**Comment by tfoote** [comment]
@JKTesla that looks like it's related to https://github.com/osrf/car_demo/pull/51 not this issue.

**Comment by tfoote** [comment]
This was resolved in #18
