### ISSUE TITLE
AUR packages

### ISSUE THREAD

**Issue by midnightexigent** [osrf/rocker#163]
I just generated and published packages the following packages in the [Arch User Repository](https://aur.archlinux.org/) meaning that it can now be installed on Arch Linux. 

- [python-rocker-git](https://aur.archlinux.org/packages/python-rocker-git/)
- [python-rocker](https://aur.archlinux.org/packages/python-rocker/)

Feel free to add that in the README

**Comment by tfoote** [comment]
Thanks for packaging it. I'd be happy to add that to the README. Could you open a PR with some proposed verbiage? I'm not closely familiar with how best to word things.

**Comment by midnightexigent** [comment]
Sure I can #167
