### ISSUE TITLE
unable to map ports

### ISSUE THREAD

**Issue by Linusnie** [osrf/rocker#176]
Hi, I find rocker very handy for mapping user privileges, enabling GUIs etc. But as far as I can tell port mapping (e.g. -p 5050:5050) doesn't work, so I have to switch back to regular docker in some situations.

Is it possible to do port mapping somehow with rocker? And if not could it be added to the interface?

**Comment by jaron-l** [comment]
Caveat: I've never used this package before nor know much about it but...

I believe you are looking for [run arg mappings](https://github.com/sloretz/off-your-rocker#docker-run-args).

**Comment by ErikKrauter** [comment]
I have the same issue. Event after the PR #201. I cannot use -p or --port with rocker.

**Comment by tfoote** [comment]
This should be covered by #201 and OYR run arg mappings. @ErikKrauter if you are still having an issue please open a new issue with instructions for how to reproduce.
