### ISSUE TITLE
Add option to not pass host user $SHELL to container when using --user?

### ISSUE THREAD

**Issue by rcywongaa** [osrf/rocker#183]
I use `zsh` in my host environment but `zsh` isn't installed in my container.  It seems with `--user`, `rocker` automatically sets the container shell to use the host user shell

https://github.com/osrf/rocker/blob/28a8e796ed7fe9b450a80a6385b3a2f56e85e3d0/src/rocker/templates/user_snippet.Dockerfile.em#L19

This causes the following warning to pop up in various places
```
Warning: missing or non-executable shell '/bin/zsh'
```

Given that a container usually has a stripped down version of the host environment, it doesn't seem like a good idea to assume the container will have/use the same shell as the host.  

Should there be an option to disable this shell setting?

**Comment by tfoote** [comment]
Yeah, an option like `--user-override-shell` might make sense similar to how you can override the username

https://github.com/osrf/rocker/blob/28a8e796ed7fe9b450a80a6385b3a2f56e85e3d0/src/rocker/extensions.py#L233-L236

**Comment by rcywongaa** [comment]
Cool!  I can work on this and submit my first PR :D

Should the default behavior (in the absence of `--user-override-shell`) be changed to use the container's default shell then, i.e. only use a different shell when explicitly provided ?
