### ISSUE TITLE
CI is broken

### ISSUE THREAD

**Issue by tfoote** [osrf/rocker#225]
github appears to have moved the action runners forward. They've dropped node 12 support which it appears checkout@v2 is using and Docker daemon is no longer installed by defaut.

**Comment by BabaYaga1221** [comment]
I think in the file ``.github/workflows/basic-ci.yaml``, we need to add 3.8 in single quotes. I don't have much knowledge about yaml files but I think this might causing the issue.

**Comment by tfoote** [comment]
Yeah, the Node.js 12 deprecation was just finalized and support removed it seems. I've switched to checkout@v3 and setup-python@v4

Those were the first issues and are resolved. 

But now there's an issue it seems in the new urllib2 version blocking connecting to the docker daemon. I thought it was that docker wasn't installed or running. But then I found:

https://github.com/docker/docker-py/issues/3113

I'm trying to debug in branch: https://github.com/osrf/rocker/tree/fix_ci
