### ISSUE TITLE
How to pass --ipc to the container?

### ISSUE THREAD

**Issue by vanem** [osrf/rocker#237]
I'm trying to set up ROS2  communication between the rocker overlay container and host (or another container). Due to shared memory transport confusion, it was suggested [here ](https://answers.ros.org/question/404240/fastdss-discovery-server-50-operational-in-docker/)to use  "network_mode: host",   "ipc: host" with docker composer ("--ipc" with docker run). Although network mode options is presend in rocker, it does not look like something similar for "--ipc" is available. Is there a way to do this?

**Comment by tfoote** [comment]
That's not currently a supported argument. It could be relatively easily added with a new extension. 

It should take the same format as Network https://github.com/osrf/rocker/blob/2b8d5abb18c829d22f290679b739dc53765198ad/src/rocker/extensions.py#L141

**Comment by vanem** [comment]
would this extension be able to help out of the box? https://github.com/sloretz/off-your-rocker
The readme says at the end "This allows adding arbitray arguments to docker run."
If so, how can this extension or others be used (installed etc) exactly?

**Comment by tfoote** [comment]
Yes, that can be used too. You want to install that into your python environment via pip. You may want to consider using rocker with this extension and others in a virtualenv depending on your deployment.

**Comment by vanem** [comment]
Thanks for the help, I was indeed able to install that extension via pip, and was able to pass the arguments that I needed. Would be nice to have this option build in!
