### ISSUE TITLE
Rocker throws DependencyMissing error on Ubuntu 24.04.

### ISSUE THREAD

**Issue by nvbln** [osrf/rocker#290]
I am creating this issue as I cannot find a new issue by @SevenFo, as suggested in issue #280.

I was following along the following guide to run a container: https://github.com/osrf/vrx/wiki/docker_install_tutorial.
As part of this guide, rocker is installed as follows (see also "Step 1" in the previous guide): https://github.com/HonuRobotics/dockwater/wiki/Install-Dependencies.

During the guide, I hit the following error as soon as I run `./run.bash dockwater:humble`:
```usage: rocker [-h] [--noexecute] [--nocache] [--nocleanup] [--pull]
              [--version] [--cuda] [--dev-helpers] [--devices [DEVICES ...]]
              [--env NAME[=VALUE] [NAME[=VALUE] ...]] [--env-file ENV_FILE]
              [--expose EXPOSE] [--git] [--git-config-path GIT_CONFIG_PATH]
              [--group-add GROUP_ADD] [--home] [--hostname HOSTNAME]
              [--name NAME]
              image [command ...]
rocker: error: DependencyMissing encountered: Docker Client failed to connect to docker daemon. Please verify that docker is installed and running. As well as that you have permission to access the docker daemon. This is usually by being a member of the docker group. The underlying error was:
"""
Error while fetching server API version: HTTPConnection.request() got an unexpected keyword argument 'chunked'
"""
```

However, simply running `rocker` without any arguments is enough to trigger this error.
I have attempted to use Docker in [rootless mode](https://docs.docker.com/engine/security/rootless/), but this didn't make a difference.

I am using Ubuntu 24.04, upgraded from 22.04.

**Comment by nvbln** [comment]
This error does not appear when installing `rocker` through pip instead:
```sudo apt purge python3-rocker
python -m venv testenv
source testenv/bin/activate
pip install rocker```

I only tested this with Docker in rootless mode.

However, when I try to run various containers, I end up with a different error:
`no more output and success not detected`.
I tested various commands:
`rocker ros:humble`
`rocker --nvidia --x11 --user --home --pull --pulse tfoote/drone_demo`
`run.bash dockwater:humble`

I'm not confident that this issue is related to the previous one however.

**Comment by tfoote** [comment]
It looks like a similar incompatibilty between docker-py and requests as #278 . I found https://github.com/docker/docker-py/issues/3113

Can you verify your versions of python3-docker and python3-requests in your environment? It appears to have been fixed: https://github.com/docker/docker-py/pull/3116 but I don't know which release it's into.

**Comment by nvbln** [comment]
Ubuntu 24.04 LTS has:
`python3-requests`: 2.31.0
`python3-docker`: 5.0.3-1

So you're correct that this is caused due to a version incompatibility, this is not an issue anymore from `python3-docker>=6.1.0` onwards. 
For future reference, since `python3-docker` is only available as 5.0.3-1 for noble. Instead I manually installed version 7.1.0-1 from oracular as the dependencies stay the same.

Afterwards everything ran as expected. Thanks!

**Comment by tfoote** [comment]
Ohh, that sounds like an issue we'll want to push on upstream with Ubuntu. Thanks for confirming that's your issue and providing a suggested workaround.

python3-docker package version in noble: https://packages.ubuntu.com/noble/python3-docker

**Comment by nvbln** [comment]
It appears a fix is fortunately already on the way: https://bugs.launchpad.net/ubuntu/+source/python-docker/+bug/2065348.
