### ISSUE TITLE
Add the ability for extensions to have requirements on other extension

### ISSUE THREAD

**Issue by tfoote** [osrf/rocker#37]
For example the nvidia extension will need the x11 extension to be useful.

Also the home extension should require the user extension for permissions.

There' s a question of ordering, required before or not. And for each sequential element aka snippets.

Preamble elements are named so order independent, and arguments are order independent as far as I know as long as they're escaped properly.

This will resolve this todo: https://github.com/osrf/rocker/blob/cea068015fd7e1026d3887c103a71d86557b5dbb/test/test_nvidia.py#L134

**Comment by stonier** [comment]
Experimenting with this at https://github.com/stonier/groot_rocker/pull/31.

Is it in the vicinity of what you were looking for?

**Comment by agyoungs** [comment]
This looks stale, but would be pretty useful for a few things I'm working on. Is there any progress on this? I'm happy to take a stab at it if the solution provided by @stonier isn't quite complete and they don't have the time to work on it at the moment.
