### ISSUE TITLE
pass through window resize logic to interactive window

### ISSUE THREAD

**Issue by tfoote** [osrf/rocker#7]
By default most things go through except for the window resize signals. 

https://pexpect.readthedocs.io/en/stable/api/pexpect.html#pexpect.spawn.interact

**Comment by ruffsl** [comment]
I'd like to help, but I don't know what is going on. Could you elaborate on what you've linked to and what signals are missing. For example, if I set the command directive to byobu of tmux in the Dockerfile:

``` Dockerfile
CMD ["byobu"]
```

The following two command do not behave the same, in that byobu from `docker run` will resize with to current xterm window size as I change it, while the byobu session from `rocker` will default to `COLUMNS=80`, `LINES=23`.

```
$ docker run -it <image>:<tag>
$ rocker <image>:<tag>
```
