### ISSUE TITLE
Network options are hardcoded

### ISSUE THREAD

**Issue by ruffsl** [osrf/rocker#70]
I feel that the `--network` arg should be using the exact string passed to it to resolve which docker network to attach to, and not assume how the networks are named on the current system.

https://github.com/osrf/rocker/blob/8f0da1f49c7240efc96ffa4ffa48101af580911e/src/rocker/cli.py#L37

**Comment by tfoote** [comment]
Yeah, those were the default ones on my system. Making it more dynamic would be great. It looks like we can get a short list to validate the arguments against by running `docker network ls --format '{{.Name}}'`
