### ISSUE TITLE
Ubuntu 20.04 support for `--nvidia`

### ISSUE THREAD

**Issue by ruffsl** [osrf/rocker#78]
Currently testing some stuff with ROS2 Foxy on Ubutu 20.04. Looks like `--nvidia` isn't supported yet:
```
WARNING distro version 20.04 not in supported list by Nvidia supported versions ['16.04', '18.04']
```

Related: https://gitlab.com/nvidia/container-images/opengl/-/issues/7

**Comment by tfoote** [comment]
@ruffsl I think I found a workaround without needing a new image from upstream. Could you try out the implementation in #83 It also seems to work for buster images.
